[package]
name = "findit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0"
chrono = "0.4"
sqlparser = {version = "0.58", features = ["bigdecimal"]}
itertools = "0.14"
regex = "1.11"

