name: Verify

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Cache Cargo registry and Git dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}        
    - name: Run check
      run: cargo check --all-targets
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Run tests
      run: cargo test
    - name: Run Format
      run: cargo fmt --all --check
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Publish dry run
      run: cargo publish --dry-run
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.32.0
    - name: Markdown link check
      uses: tcort/github-action-markdown-link-check@v1
    - name: Markdown lint
      uses: DavidAnson/markdownlint-cli2-action@v22
      with:
        globs: '**/*.md'
